version: '3.8'

services:
  spam-filter-service:
    container_name: spam-filter
    image: spam-filter-service:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8567:8567"